# Training Academy Module Configuration
# AI-First training and onboarding system

module:
  name: TrainingAcademy
  version: 1.0.0
  description: AI-First training and onboarding system with gamification
  enabled: true
  priority: high
  
capabilities:
  - type: onboarding
    description: Interactive AI-first onboarding for new users
    priority: critical
    
  - type: feature_training
    description: Training on all AI-first features
    priority: high
    
  - type: skill_assessment
    description: Continuous skill assessment and feedback
    priority: medium
    
  - type: continuous_learning
    description: Adaptive learning based on user progress
    priority: medium
    
  - type: certification
    description: AI mastery certification system
    priority: low

intents:
  training:
    - "i want to learn"
    - "teach me"
    - "show me how"
    - "how do i"
    - "training"
    - "learn about"
    
  onboarding:
    - "i'm new"
    - "getting started"
    - "first time"
    - "onboarding"
    - "new user"
    
  help:
    - "help"
    - "i need help"
    - "can you help"
    - "assist me"
    - "guide me"
    
  tutorial:
    - "tutorial"
    - "walkthrough"
    - "demonstration"
    - "show me"

modules:
  week1:
    - ai_first_onboarding
    - voice_interaction_training
    - ai_profile_creation_workshop
    
  week2:
    - ai_document_generation_training
    - emotional_ai_integration_module
    - swiss_compliance_ai_training
    - ai_job_matching_training
    
  week3:
    - predictive_analytics_training
    - multilanguage_ai_support
    - ai_automation_training
    
  week4:
    - ai_mastery_assessment
    - continuous_optimization

infrastructure:
  - interactive_tutorial_system
  - assessment_validation_system
  - skill_progression_tracker
  - performance_analytics_system

settings:
  default_path: quick_start
  daily_commitment_minutes: 30
  gamification_enabled: true
  adaptive_learning: true
  voice_guidance: true
  
integration:
  mcp_agents:
    - training_specialist
    - learning_coach
    - assessment_evaluator
    
  conversation_handler: TrainingCompanion
  curriculum_manager: CurriculumManager