
apiVersion: v1
kind: Namespace
metadata:
  name: biological-production
  labels:
    name: biological-production
    environment: production
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: biological-logs-pvc
  namespace: biological-production
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
