
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: biological-pod-reader
  namespace: biological-production
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: biological-read-pods
  namespace: biological-production
subjects:
- kind: ServiceAccount
  name: biological-monitoring
  namespace: biological-production
roleRef:
  kind: Role
  name: biological-pod-reader
  apiGroup: rbac.authorization.k8s.io
